# Dockerfile describing a container image for the Chuck Norris web application.
# Base image for the container
FROM nginx:1.27-alpine
# Build time command
RUN apk add --no-cache curl
COPY docker/nginx.conf /etc/nginx/nginx.conf